version: "3.9"

services:
    db:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-Postgis
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: development
            POSTGRES_USER: developer
            POSTGRES_PASSWORD: password
        volumes:
            - ./docker/init-postgres-scripts:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
