version: "3.9"

services:
    db:
        image: postgres:15.2
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: developer
            POSTGRES_PASSWORD: password
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
